### ISSUE TITLE
UI Component is inside the Spring Project

### ISSUE THREAD

**Issue by Skrinikov** [ArchambaultP/Comp354Website#27]
Angular project is inside the Spring folder. 
This is an unnecessary nesting of unrelated components. This is not production quality code

Proposed Solution:
Extract Angular project outside the spring folder to be a the same level as the backend.
Compile both separately

**Comment by ArchambaultP** [comment]
The reason the ui project is in there is to simplify editing in intelliJ. Both components already compile separately. Extracting the project into its own directory will not provide  any updated readability or features to the code; the front end part of the project is already well isolated as it is.

I think it would be best to leave it as is, and focus on more important stuff, like the project itself
